### ISSUE TITLE
Vultr /DO  snapshot, application (apps) provision for VM request

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#47]
hello , 

it would be nice to add the feature of provisioning VM via Vultr or DO backbone with snapshot, custom ISO, backup, application (apps) for Vultr and  snapshot, application (apps) for DO .

Thanks

**Comment by uakfdotb** [comment]
Snapshots on Digital Ocean should work. If you take a snapshot, then it should be automatically inserted into the images table. If you want to manually associate an existing snapshot with Lobster, the image identification is "snapshot:" followed by the snapshot name.

ISO and snapshots on Vultr should also work. For ISO, prefix the image ID with "iso:" instead of "os:". For snapshots, prefix it with "snapshot:". If you take a snapshot from Lobster, again it should automatically be associated in the database.

Applications aren't supported though, and support can certainly be added.

**Comment by rezabagh** [comment]
hello, 
for the Vultr i created a VM with snapshot , but i get the below error, it still need OSID.

i have create the record like this : my custom	-1	 Plan Amsterdam 	Active  snapshot:bc55217eaf988


error : 

Hi,

Lobster panel encountered an error.

Error: Missing OSID field
Description: vm creation failed
Detail:
hostname=wsws, plan_id=125, image_identification=snapshot:bc55217eaf988

This error should be resolved as soon as possible!

**Comment by uakfdotb** [comment]
The issue with provision from snapshot has been fixed.

**Comment by uakfdotb** [comment]
Applications are now supported on the vultr provider on Cloug. To use this in Lobster, add block to lobster.cfg.json like this:

		{
			"name": "Vultr NJ",
			"type": "cloug",
			"provider": "vultr",
			"region": "1",
			"api_key": "YOUR API KEY"
		}

**Comment by rezabagh** [comment]
hello, 

Thank you for great support , how i should define the image ID for creating a specific Applications ?

Thanks

**Comment by uakfdotb** [comment]
It would be app:[APPID]. The autopopulate function will include the application images. You'll need to use the Cloug provider with the JSON configuration above, this supercedes the direct Lobster VMI.

**Comment by rezabagh** [comment]
hello, 

Thank you @uakfdotb for your hint, at this would work for digitalocean as well ? i mean "type": "cloug", and image ID "app:[APPID]" or there should be some difference ?

**Comment by uakfdotb** [comment]
No, for DigitalOcean you would just specify the image ID of the application image. On DO, distributions/applications/snapshots all have the same ID scheme; Vultr needs special distinction because each image type is treated differently.
